### ISSUE TITLE
rbac.authorization.k8s.io/v1beta1 deprecated warning

### ISSUE THREAD

**Issue by ArgTang** [haproxy-ingress/charts#17]
> Warning: rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+;

Chart should at some point use the new one or use a capabilities check to change api

**Comment by jcmoraisjr** [comment]
Thanks for reporting this! I'll have a look before tagging a new release.

**Comment by jcmoraisjr** [comment]
v0.12 has minimum kubernetes version as 1.18, so changing api to v1 without side effect. This will be included in the new v0.12 and v0.13 releases. Thanks! Closing.
