### ISSUE TITLE
haproxy-ingress fails with 'cannot list resource "ingresses" in API group "networking.k8s.io'

### ISSUE THREAD

**Issue by ieugen** [haproxy-ingress/charts#3]
I've installed haproxy-ingress on k3s v1.19.3+k3s3.
A fresh cluster.

```
    helm repo add haproxy-ingress https://haproxy-ingress.github.io/charts
    helm repo update

    helm install haproxy-ingress haproxy-ingress/haproxy-ingress \
    --create-namespace --namespace=ingress-controller \
    --set controller.hostNetwork=true \
    --set controller.kind=DaemonSet \
    --set controller.image.tag=v0.11-beta.3
```
I got an error that I managed to fix by following the guide here: https://github.com/kubernetes/ingress-nginx/issues/4296#issuecomment-509565573 .

```
E1116 19:43:38.325095       7 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125: Failed to list *v1beta1.Ingress: ingresses.networking.k8s.io is forbidden: User "system:serviceaccount:ingress-controller:haproxy-ingress" cannot list resource "ingresses" in API group "networking.k8s.io" at the cluster scope
```

**Comment by jcmoraisjr** [comment]
Hi, this is due to an incompatibility between the cluster role configuration (v0.10) and deployed image (v0.11). I've updated the getting started guide to suggest changing the chart version instead.

**Comment by ieugen** [comment]
Thanks. I saw your note. It's helpful.
What I always do is I specify the version.
You always want to have reproducible installs.
You only want the latest when you are testing things out or want to see how it looks.

For guides and tutorials and instructions I explicitly put the version.
I want other people that follow my work to have consistent results.

I saw cert-manager does this https://cert-manager.io/docs/installation/kubernetes/#steps

```
# Helm v3+
$ helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --version v1.0.4 \
  # --set installCRDs=true
```
Closing the issue, thanks again for your help.
