### ISSUE TITLE
PSP, ClusterRole fixes and other additions

### ISSUE THREAD

**Issue by rdavyd** [haproxy-ingress/charts#5]
Hi,

I want to propose some changes.

Fixes:
- There were problems when using **_PodSecurityPolicy_** because of wrong PSP apiGroup name. Set proper name and rewritten a bit.
- Added **_ingressclasses_** to allowed resources for **_ClusterRole_**, because operator was throwing errors on it.

Additions:
- Separate PSP for default backend.
- Added optional **_ServiceMonitor_**.

Tested all this on 1.18.10 kubernetes version with PSP enabled.

Can I make a PR on this?

**Comment by jcmoraisjr** [comment]
Hey there, yes please, PRs welcome!

**Comment by brandocorp** [comment]
It would be nice to have the PodSecurityPolicy fixed. It looks like @rdavyd took care of it in #6. What are the odds of getting that merged into master and released? :sweat_smile:

**Comment by jcmoraisjr** [comment]
Yep, planning to tag some haproxy ingress branches their charts this weekend, just after revise and merge #6 .

**Comment by rdavyd** [comment]
Thanks for  merging!
