### ISSUE TITLE
Default values prevent AKS from upgrading Kubernetes version and node image

### ISSUE THREAD

**Issue by jesuslpm** [haproxy-ingress/charts#69]
PodDisruptionBudget prevents cluster from upgrading when controller.replicaCount = 1. I would like to suggest you to change controller.replicaCount default value to 2.

**Comment by jcmoraisjr** [comment]
Makes sense, thanks for sharing. I'd however add a PodDisruptionBudget only if minAvailable is between 1 and replicas-1, what do you think? #73 implements that approach.

**Comment by jcmoraisjr** [comment]
Should be solved in the next controller releases. Closing.

**Comment by jesuslpm** [comment]
Thank you. I think adding a PodDisruptionBudget only if minAvailable is between 1 and replicas-1 is a good idea.
