### ISSUE TITLE
Missing resource for RBAC ClusterRole

### ISSUE THREAD

**Issue by seanmcconkey** [haproxy-ingress/charts#9]
I was getting the following from the haproxy-ingress pod logs.

`E0105 11:11:35.101979       6 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.0/tools/cache/reflector.go:156: Failed to watch *v1beta1.IngressClass: failed to list *v1beta1.IngressClass: ingressclasses.networking.k8s.io is forbidden: User "system:serviceaccount:ingress-controller:haproxy-ingress" cannot list resource "ingressclasses" in API group "networking.k8s.io" at the cluster scope`

I had to edit the ClusterRole manually and change the following from

```
 - apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
```

to

```
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  - ingressclasses
  - 
```

Not sure if I was missing something in my values.yaml file though nothing was obvious to me.

**Comment by seanmcconkey** [comment]
Having just checked your charts I see this was updated 19 days ago and is present.

**Comment by jcmoraisjr** [comment]
Yep, missing a new release also updating the default controller version. Taking care of this in the next few days.
